### ISSUE TITLE
Don't use LruCache

### ISSUE THREAD

**Issue by nk-coding** [ls1intum/artemis-java-test-sandbox#63]
**Is your feature request related to a problem? Please describe.**
We have a dependency which
* uses the Java 9 module system
* has dependencies to junit framework and engine

LruCache is in the module org.junit.platform.commons.util, which is not exported, which then causes issues (the class def is not found)

**Describe the solution you'd like**
Not use the LruCache (maybe an own implementation instead? It basically just overwrites LinkedHashMap.removeEldestEntry)

**Describe alternatives you've considered**
\-

**AJTS-Version you are using**
1.3.2

**Comment by MaisiKoleni** [comment]
Yes, I can change that, of course. I thought it would be a good idea to avoid having yet another LRU implementation, but this is a problem, of course (it would also be one for #10). I will this that today.

**Comment by MaisiKoleni** [comment]
This should now be fixed in version `1.3.4` with commit defb7ae6acf430d6e97443ededf4f32f320826a7.
