### ISSUE TITLE
Handle recursive file access permissions

### ISSUE THREAD

**Issue by ColoredCarrot** [ls1intum/artemis-java-test-sandbox#78]
### Description

`ArtemisSecurityManager` checks `FilePermission`s calling `Path.of` on the permission name (see [here](https://github.com/ls1intum/artemis-java-test-sandbox/blob/c62a5bc634f79a8a6d5e179e43acfc549b7ac7a4/src/main/java/de/tum/in/test/api/security/ArtemisSecurityManager.java#L353)). `FilePermission` names are allowed to end with either `-` or `*` to indicate recursive or directory access, respectively, which `Path.of` does not handle specially; a path to a file named `-` or `*` is created instead.

The created path is checked in `checkPathAccess`, which compares it to the whitelist and blacklist. No special handling for directory or recursive permissions is performed. I do not believe this to be intended behavior; if it is, it is not documented.

Additionally, the token `<<ALL FILES>>` is not handled, which should always be denied from my perspective.

### Security

If access to a file named `x/-` is granted based on the whitelist containing an entry for a file named `x/-`, this presents a *potential* security vulnerability, as Java will allow access to all files in the directory `x`, *recursively*. However, this seems like an unlikely scenario to actually occur, since modifying the whitelist is not permitted for student code and files named `-` are not expected to be used.

Additionally, a `FilePermission` with such a path seems to never actually be constructed, at least on Windows. Working under the assumption that `WindowsPath.path` will never hold such a value (this assumption is not insignificant), I was unable to find a codepath by which the Windows file system would construct a `FilePermission` with one of the mentioned special tokens.

Since `ArtemisSecurityManager` denies access to instrumentation (which I discovered after some admittedly short testing), it is not trivial to dynamically replace the loaded bytecode of `WindowsPath` (or whatever the Linux equivalent may be), which would allow for circumventing the security check altogether.

### Conclusion

In my opinion, this issue does not represent a security risk or a bug in the current Java ecosystem. However, it is not robust against potential future changes to the Java internals which might make use of recursive file access permissions.

Still, it should be considered handling (favorably outright denying) any file permissions whose path either ends in `/*` or `/-` or equals `*` or `-` or `<<ALL FILES>>`.

**AJTS version**: 1.4.6

**Comment by MaisiKoleni** [comment]
Thanks, I will have a look at that.

**Comment by MaisiKoleni** [comment]
In case the solution I provided is faulty or does not meet your needs, feel free to reopen this issue.
